# Generated by Django 4.2.1 on 2023-07-30 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('dob', models.DateField()),
                ('gender', models.CharField(max_length=70)),
                ('locality', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(choices=[('KL', 'Kerala'), ('UP', 'Uttar Pradesh'), ('HP', 'Himachal Pradesh'), ('MZ', 'Mizoram'), ('OD', 'Odisha'), ('RJ', 'Rajasthan'), ('WB', 'West Bengal'), ('GJ', 'Gujarat'), ('MP', 'Madhya Pradesh'), ('JK', 'Jammu and Kashmir'), ('CG', 'Chhattisgarh'), ('HR', 'Haryana'), ('DN', 'Dadra and Nagar Haveli'), ('DD', 'Daman and Diu'), ('AN', 'Andaman and Nicobar Islands'), ('BR', 'Bihar'), ('AP', 'Andhra Pradesh'), ('NL', 'Nagaland'), ('PB', 'Punjab'), ('MH', 'Maharashtra'), ('JH', 'Jharkhand'), ('MN', 'Manipur'), ('TS', 'Telangana'), ('LA', 'Ladakh'), ('DL', 'Delhi'), ('UK', 'Uttarakhand'), ('AS', 'Assam'), ('KA', 'Karnataka'), ('TN', 'Tamil Nadu'), ('LD', 'Lakshadweep'), ('SK', 'Sikkim'), ('ML', 'Meghalaya'), ('PY', 'Pondicherry'), ('GA', 'Goa'), ('CH', 'Chandigarh'), ('TR', 'Tripura'), ('AR', 'Arunachal Pradesh')], max_length=50)),
                ('pincode', models.PositiveIntegerField()),
                ('mobile', models.PositiveIntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('job_city', models.CharField(max_length=70)),
                ('profile_image', models.ImageField(blank=True, upload_to='profileimg')),
                ('my_file', models.ImageField(blank=True, upload_to='doc')),
            ],
        ),
    ]
